project:
  type: website
  output-dir: docs
  resources:
    - "cv/**"
    - "schemeStata/**"

website:
  title: "ATK"
  description: "Andrew Taeho Kim is an Assistant Professor of Sociology at the University of Tennessee, Knoxville."
  favicon: images/800px-UT_Knoxville_logo_2015.png
  navbar:
    title: false
    logo: images/800px-UT_Knoxville_logo_2015.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv/atkim_cv_202607.pdf
        text: CV
        target: _blank
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact

    # right:
      # - icon: github
      #   href: https://github.com/atkim1
      #   aria-label: GitHub

  page-footer:
    left: "© 2026 Andrew Taeho Kim"
    right: "Built with Quarto and GitHub"

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    # theme: cyborg
    # css: styles.css
    mainfont: Montserrat
    fontsize: 0.95rem
    toc: true
    smooth-scroll: true
    link-external-newwindow: true