---
title: "Links"
---

## University and test

[UTK: Department of Sociology](https://sociology.utk.edu/) $\cdot$
[UTK: Outlook](https://outlook.cloud.microsoft/mail/)
$\cdot$
[UTK: UT Verse](https://utverse.tennessee.edu/)
$\cdot$
[UTK: AIHub](https://aihub.tennessee.edu/)
$\cdot$
[UTK: myUTK](https://myutk.utk.edu/)
$\cdot$
[UTK: DASH](https://dash.tennessee.edu/home)
$\cdot$
[UTK: Library](https://www.lib.utk.edu/)
$\cdot$
[UTK: Canvas](https://utk.instructure.com/)
$\cdot$
[UTK: Class Schedule](https://bannerssb.utk.edu/kbanpr/bwckschd.p_disp_dyn_sched)
$\cdot$
[UTK: Zoom](https://tennessee.zoom.us/)
$\cdot$
[UTK: Office of Innovative Technologies](https://oit.utk.edu/)
$\cdot$
[UTK: Tennessee State Data Center](https://tnsdc.utk.edu/)
$\cdot$
[UTK: K@TE](https://kate.tennessee.edu/)
$\cdot$
[UTK: Pivot](https://pivot.proquest.com/)
$\cdot$
[UTK: Workshops](https://workshop.utk.edu/)
$\cdot$
[UTK: Elements](https://elements.utk.edu/)
$\cdot$
[UTK: Faculty](https://faculty.utk.edu/Andrew.Kim/about)
$\cdot$
[UTK: Planning](https://planning.utk.edu/)
$\cdot$
[UTK: Calendar](https://calendar.utk.edu/)
$\cdot$
[UTK: Center for the Study of Family Health and Well-Being](https://csfhw.utk.edu/)
$\cdot$
[Sam Kendrick](https://www.sam-kendrick.com/)

[KU: Department of Sociology](https://sociology.ku.edu/)
$\cdot$
[KU: Institute for Policy & Social Research](https://ipsr.ku.edu/)
$\cdot$
[KU: Kansas Population Center](https://kpc.ku.edu/)
$\cdot$
[KU: Enroll & Pay](https://sa.ku.edu/)
$\cdot$
[ChangHwan Kim](https://www.changhwankim.net/)

[PENN: Population Studies Center](https://www.pop.upenn.edu/)
$\cdot$
[PENN: Department of Sociology](https://sociology.sas.upenn.edu/)
$\cdot$
[PENN: Population Aging Research Center](https://parc.pop.upenn.edu/)
$\cdot$
[PENN: James Joo-Jin Kim Center for Korean Studies](https://korea.sas.upenn.edu/)
$\cdot$ [PENN: Education & Inequality Research Cluster](https://web.sas.upenn.edu/education-and-inequality-workshop/)

## Work

[Overleaf](https://www.overleaf.com/project)
$\cdot$
[GitHub](https://github.com/)
$\cdot$
[Gmail](https://mail.google.com/mail/)
$\cdot$
[Calendly](https://www.calendly.com/)
$\cdot$
[Google Calendar](https://calendar.google.com/calendar/r)
$\cdot$
[Google Sites](https://sites.google.com/)
$\cdot$
[Squarespace](https://www.squarespace.com/)
$\cdot$
[Oxford English Dictionary](https://www.oed.com/)

## References

[American Sociological Review](https://journals.sagepub.com/home/asr)
$\cdot$
[American Journal of Sociology](https://www.journals.uchicago.edu/toc/ajs/current)
$\cdot$
[Annual Review of Sociology](https://www.annualreviews.org/journal/soc)
$\cdot$
[Social Forces](https://academic.oup.com/sf)
$\cdot$
[Social Science Research](https://www.sciencedirect.com/journal/social-science-research)
$\cdot$
[European Sociological Review](https://academic.oup.com/esr)
$\cdot$
[Social Problems](https://academic.oup.com/socpro)
$\cdot$
[Sociological Science](https://sociologicalscience.com/)
$\cdot$
[Socius: Sociological Research for a Dynamic World](https://journals.sagepub.com/home/SRD)
$\cdot$
[RSF: The Russell Sage Foundation Journal of the Social Sciences](https://www.rsfjournal.org/)

[Sociological Methods & Research](https://journals.sagepub.com/home/smr)
$\cdot$
[Sociological Methodology](https://journals.sagepub.com/home/smx)
$\cdot$
[Research in Social Stratification and Mobility](https://www.sciencedirect.com/journal/research-in-social-stratification-and-mobility)
$\cdot$
[Work and Occupations](https://journals.sagepub.com/home/wox)
$\cdot$
[Work, Employment and Society](https://journals.sagepub.com/home/wes)
$\cdot$
[Socio-Economic Review](https://academic.oup.com/ser)
$\cdot$
[Sociology of Education](https://journals.sagepub.com/home/soe)
$\cdot$
[Journal of Marriage and Family](https://onlinelibrary.wiley.com/journal/17413737)
$\cdot$
[Gender & Society](https://journals.sagepub.com/home/gas)
$\cdot$
[Journal of Family Theory & Review](https://onlinelibrary.wiley.com/journal/17562589)
$\cdot$
[Ethnic and Racial Studies](https://www.tandfonline.com/journals/rers20)
$\cdot$
[Sociology of Race and Ethnicity](https://journals.sagepub.com/home/sre)
$\cdot$
[Du Bois Review](https://www.cambridge.org/core/journals/du-bois-review-social-science-research-on-race)
$\cdot$
[International Migration Review](https://journals.sagepub.com/home/mrx)
$\cdot$
[Journal of Ethnic and Migration Studies](https://www.tandfonline.com/journals/cjms20)

[Demography](https://read.dukeupress.edu/demography)
$\cdot$
[Population Research and Policy Review](https://link.springer.com/journal/11113)
$\cdot$
[Demographic Research](https://www.demographic-research.org/volumes/articles.htm)
$\cdot$
[Population and Development Review](https://onlinelibrary.wiley.com/journal/17284457)

[Sociological Theory](https://journals.sagepub.com/home/STX)
$\cdot$
[Theory and Social Inquiry](https://www.theoryandsocialinquiry.org/)
$\cdot$
[Theory and Society](https://link.springer.com/journal/11186)

[Science](https://www.science.org/journal/science)
$\cdot$
[Nature](https://www.nature.com/)
$\cdot$
[PNAS](https://www.pnas.org/)
$\cdot$
[American Economic Review](https://www.aeaweb.org/journals/aer)
$\cdot$
[Journal of Economic Literature](https://www.aeaweb.org/journals/jel)
$\cdot$
[Journal of Economic Perspectives](https://www.aeaweb.org/journals/jep)
$\cdot$
[Quarterly Journal of Economics](https://academic.oup.com/qje/issue)
$\cdot$
[Annual Review of Economics](https://www.annualreviews.org/journal/economics)
$\cdot$
[Administrative Science Quarterly](https://journals.sagepub.com/home/asq)

[JSTOR](https://www.jstor.org/)
$\cdot$
[NBER Working Papers](https://www.nber.org/papers)
$\cdot$
[IZA Discussion Papers](https://www.iza.org/en/publications/dp?page=1)
$\cdot$
[OSF Preprints](https://osf.io/preprints/)
$\cdot$
[Pew Research Center](https://www.pewresearch.org/)

[Foundations and Futures: Asian American and Pacific Islander Multimedia Textbook](https://www.foundationsandfutures.org/)

## Organizations

[American Sociological Association](https://www.asanet.org/)
$\cdot$
[ASA Portal](https://my.asanet.org/)
$\cdot$
[International Sociological Association](https://www.isa-sociology.org/)
$\cdot$
[Midwest Sociological Society](https://www.themss.org/)
$\cdot$
[Social Science History Association](https://ssha.org/)
$\cdot$
[Southern Sociological Society](https://www.southernsociologicalsociety.org/)

[ASA: Family](https://www.asafamilysection.com/)
$\cdot$
[ASA: Organizations, Occupations and Work](https://oowsection.org/)

[ISA: RC28 Social Stratification and Mobility](https://sites.google.com/site/rc28hp/)

[Population Association of America](https://www.populationassociation.org/)
$\cdot$
[Southern Demographic Association](https://sda-demography.org/)

[Association for Asian American Studies](https://aaastudies.org/)
$\cdot$
[AAAS-SocSci](https://sites.google.com/view/aaas-socsci/home?authuser=0)
$\cdot$
[Association for Asian Studies](https://www.asianstudies.org/)
$\cdot$
[PDX: Institute for Asian Studies](https://www.pdx.edu/asian-studies/)
$\cdot$
[Columbia: The Asian American Initiative](https://aai.fas.columbia.edu/)
$\cdot$
[UCLA: Asian American Studies Center](https://www.aasc.ucla.edu/)
$\cdot$
[Stanford: Walter H. Shorenstein Asia-Pacific Research Center](https://aparc.fsi.stanford.edu/)

[Association of Korean Sociologists in America](https://koreansociologists.wixsite.com/aksa)
$\cdot$
[Korean Inequality Research Network](https://inequality.kr/)
$\cdot$
[Korean Sociological Association](https://www.ksa21.or.kr/)
$\cdot$
[Population Association of Korea](https://pak.re.kr/)

[AAPI Data](https://aapidata.com/)
$\cdot$
[AmplifyAAPI](https://amplifyaapi.norc.org/)
$\cdot$
[Berkeley: Population Center](https://populationsciences.berkeley.edu/population-center/)
$\cdot$
[Center for Inequality Dynamics](https://www.inequalitydynamics.umich.edu/)
$\cdot$
[Economic Policy Institute](https://www.epi.org/)
$\cdot$
[Formal Demography Working Group](https://formaldemography.github.io/working_group/)
$\cdot$
[Human Capital and Economic Opportunity Global Working Group](https://hceconomics.uchicago.edu/)
$\cdot$
[OSU: Institute for Population Research](https://ipr.osu.edu/)
$\cdot$
[Minnesota: Population Center](https://pop.umn.edu/)
$\cdot$
[National Council on Family Relations](https://www.ncfr.org/)
$\cdot$
[National Institutes of Health](https://www.nih.gov/)
$\cdot$
[National Science Foundation](https://www.nsf.gov/)
$\cdot$
[PSU: Population Research Institute](https://pop.psu.edu/)
$\cdot$
[Poverty & Policy Work Group](https://www.exppov.org/)
$\cdot$
[Russell Sage Foundation](https://www.russellsage.org/)
$\cdot$
[Shaping the Future of Work](https://shapingwork.mit.edu/)
$\cdot$
[Stanford: Center on Poverty & Inequality](https://inequality.stanford.edu/)
$\cdot$
[Washington Center for Equitable Growth](https://equitablegrowth.org/)
$\cdot$
[Wisconsin: Institute for Research on Poverty](https://www.irp.wisc.edu/)
$\cdot$
[Work and Family Researchers Network](https://wfrn.org/)
$\cdot$
[Yale: Institution for Social and Policy Studies](https://isps.yale.edu/)

## Miscellaneous

[Sociological Evidence](https://sovidence.tistory.com/)
$\cdot$
[New York Times](https://www.nytimes.com/)
$\cdot$
[AAPI Data](https://aapidata.com/)
$\cdot$
[Asia Society](https://asiasociety.org/)
$\cdot$
[Chronicle of Higher Education](https://www.chronicle.com/)
$\cdot$
[Khan Academy](https://www.khanacademy.org/)
$\cdot$
[Opportunity Insights](https://opportunityinsights.org/)
$\cdot$
[Statistical Horizons Blog](https://statisticalhorizons.com/blog/)
$\cdot$
[The Society Pages](https://thesocietypages.org/)
$\cdot$
[Vox](https://www.vox.com/)
$\cdot$
[Vox: EU](https://voxeu.org/)
$\cdot$
[Work in Progress](https://www.wipsociology.org/)
$\cdot$
[Purdue Online Writing Lab](https://owl.purdue.edu/)
$\cdot$
[Sociomechanics](https://sociomechanics.com/)

[Clem Aeppli](https://clemaeppli.github.io/)
$\cdot$
[Alan Agresti](https://users.stat.ufl.edu/~aa/)
$\cdot$
[David Brady](https://bradydave.wordpress.com/)
$\cdot$
[Jessica Calarco](https://www.jessicacalarco.com/)
$\cdot$
[Siwei Cheng](https://siwei-cheng.github.io/)
$\cdot$
[Raj Chetty](https://www.rajchetty.com/)
$\cdot$
[Seongsoo Choi](https://sites.google.com/view/seongsoo-choi/home)
$\cdot$
[Yool Choi](https://cyoolc.wixsite.com/ychoi)
$\cdot$
[Sergio Correia](https://scorreia.com/)
$\cdot$
[David Dorn](https://www.ddorn.net/data.htm)
$\cdot$
[Econbigdata](https://econbigdata.tistory.com/)
$\cdot$
[Economists' View](https://economistsview.typepad.com/)
$\cdot$
[Per Engzell](https://perengzell.com/)
$\cdot$
[Family Inequality](https://familyinequality.wordpress.com/)
$\cdot$
[Jeremy Fiel](https://jeremyefiel.com/)
$\cdot$
[Brenda Gambol](https://brendagambol.com/)
$\cdot$
[Andrew Gelman](https://statmodeling.stat.columbia.edu/)
$\cdot$
[Ohjae Gowen](https://www.ohjaegowen.com/)
$\cdot$
[Sang Won Han](https://www.sangwonhan.com/)
$\cdot$
[Sinn Won Han](https://www.sinnwonhan.com/)
$\cdot$
[Nanum Jeon](https://www.nanumjeon.org/)
$\cdot$
[Todd Jones](https://www.toddrjones.com/)
$\cdot$
[Lisa Kaida](https://lisakaida.com/)
$\cdot$
[Rebecca A. Karam](https://rebeccakaram.com/)
$\cdot$
[Lane Kenworthy](https://lanekenworthy.net/)
$\cdot$
[Tate Kihara](https://tatekihara.com/)
$\cdot$
[Minjae Kim](https://minjae-kim.com/)
$\cdot$
[Nicole Kreisberg](https://www.nicolekreisberg.com/)
$\cdot$
[Paul Krugman](https://www.nytimes.com/column/paul-krugman)
$\cdot$
[Byungkyu Lee](https://www.byungkyulee.com/)
$\cdot$
[Heeyoung Lee](https://idlhy0218.github.io/)
$\cdot$
[Jiwon Lee](https://jiwonlee.net/)
$\cdot$
[Sangsoo Lee](https://www.sangsoolee.com/)
$\cdot$
[Dan Little](https://danlittle.org/)
$\cdot$
[Understanding Society](https://understandingsociety.blogspot.com/)
$\cdot$
[Ian Lundberg](https://www.ianlundberg.org/)
$\cdot$
[Robert Manduca](https://robertmanduca.com/)
$\cdot$
[Blaise Melly](https://sites.google.com/site/blaisemelly/home)
$\cdot$
[Trenton Mize](https://www.trentonmize.com/home)
$\cdot$
[Benjamin Moll](https://benjaminmoll.com/)
$\cdot$
[Marc-Andreas Muendler](https://econweb.ucsd.edu/~muendler/)
$\cdot$
[Fabian Pfeffer](https://fabianpfeffer.com/)
$\cdot$
[Alec P. Rhodes](https://www.alecprhodes.com/)
$\cdot$
[Fernando Rios-Avila](https://friosavila.github.io/)
$\cdot$
[Evan K. Rose](https://ekrose.github.io/)
$\cdot$
[Tahseen Shams](https://www.tahseenshams.org/)
$\cdot$
[Haoming Song](https://haomingsong.digitalscholarship.brown.edu/)
$\cdot$
[Xi Song](https://www.xisong.me/)
$\cdot$
[Pildoo Sung](https://pildoo.github.io/)
$\cdot$
[Tom VanHeuvelen](https://www.tomvanheuvelen.com/)
$\cdot$
[A Social Substack](https://asocial.substack.com/)
$\cdot$
[Deadric T. Williams](https://deadricwilliams.wordpress.com/)
$\cdot$
[Nathan Wilmers](https://www.nathanwilmers.com/)
$\cdot$
[Geoffrey T. Wodtke](https://gtwodtke.com/)
$\cdot$
[Yu Xie](https://scholar.princeton.edu/yuxie)
$\cdot$
[Letian Zhang](https://www.letianzhang.com/)
$\cdot$
[Hui Zheng](https://www.huizhenghome.com/)

## Data

[AP-NORC](https://apnorc.org/)
$\cdot$
[IPUMS: USA](https://usa.ipums.org/usa/)
$\cdot$
[IPUMS: CPS](https://cps.ipums.org/cps/)
$\cdot$
[IPUMS: ATUS](https://www.atusdata.org/atus/)
$\cdot$
[IPUMS: Higher Ed](https://highered.ipums.org/highered/)
$\cdot$
[IPUMS: NHIS](https://nhis.ipums.org/nhis/)
$\cdot$
[CEPR Uniform Data Extracts](https://ceprdata.org/)
$\cdot$
[Consumer Expenditure Survey](https://www.bls.gov/cex/)
$\cdot$
[Future of Families and Child Wellbeing Study](https://ffcws.princeton.edu/)
$\cdot$
[FRED Economic Data](https://fred.stlouisfed.org/)
$\cdot$
[General Social Survey](https://gss.norc.org/)
$\cdot$
[Health and Retirement Study](https://hrs.isr.umich.edu/)
$\cdot$
[International Social Survey Programme](https://issp.org/)
$\cdot$
[Inter-University Consortium for Political and Social Research](https://www.icpsr.umich.edu/sites/icpsr/home)
$\cdot$
[Luxembourg Income Study](https://www.lisdatacenter.org/our-data/)
$\cdot$
[National Longitudinal Surveys](https://www.nlsinfo.org/content/cohorts/nlsy79)
$\cdot$
[National Survey of Family Growth](https://www.cdc.gov/nchs/nsfg/index.htm)
$\cdot$
[O*NET](https://www.onetcenter.org/database.html)
$\cdot$
[Panel Study of Income Dynamics](https://psidonline.isr.umich.edu/default.aspx)
$\cdot$
[Wisconsin Longitudinal Study](https://wls.wisc.edu/)
$\cdot$
[American Community Survey Data Users Group](https://acsdatacommunity.prb.org/)
