---
title: "Publications before 2023"
filters: [details]
---

## 2022

### Who Is the “She” in the Pandemic “She-Cession”? Variation in COVID-19 Labor Market Outcomes by Gender and Family Status
*Population Research and Policy Review* 41(3): 1325–1358  
Kim, Andrew Taeho, Matt Erickson, Yurong Zhang, and ChangHwan Kim  
[Article](https://doi.org/10.1007/s11113-021-09693-0)  
Media coverage: [Journalist's Resource](https://journalistsresource.org/race-and-gender/motherhood-penalty-research-covid/)

::: {.details summary="Abstract" group="faq"}
- The sharp decline in employment after the COVID-19 lockdown was not uniformly felt across demographic groups. Utilizing the 2017 to 2020 monthly Current Population Survey and using a difference-in-difference design, we investigate the varying impacts of COVID-19 on at-work status among the prime-working-age population, accounting for typical seasonal fluctuations in employment. The target population is grouped by gender, marital status, parenthood, and level of education. Our results uncover complex variations by gender, marital status, and children’s age. Contrary to popular belief, married women without school-aged children did not experience a relative decline in employment compared to married fathers. A majority of disadvantages in employment that married women experienced are accounted for by controlling for typical seasonal fluctuations. The women whose employment was most distinctively adversely affected by COVID-19 during 2020 were less-educated never-married childless women and never-married mothers. Less-educated men who were not currently married also experienced a disadvantage in employment relative to equally educated married fathers. These findings imply that, during the pandemic recession, marriage offered a form of within-family insurance that we call the "added caregiver effect." The further implications of these findings are discussed.
:::

## 2021

### COVID-19 and the Decline in Asian American Employment
*Research in Social Stratification and Mobility* 71: 100563  
Kim, Andrew Taeho, ChangHwan Kim, Scott E. Tuttle, and Yurong Zhang  
[Article](https://doi.org/10.1016/j.rssm.2020.100563)  
Media coverage: [Lawrence Journal-World](https://www2.ljworld.com/news/ku/2020/oct/21/ku-study-finds-asian-americans-hit-hardest-by-covid-19-unemployment-but-exactly-why-is-unclear/), [Donga Science](https://www.dongascience.com/news.php?idx=40864), [Business Insider](https://www.businessinsider.com/asian-americans-hit-hardest-by-covid-19-related-unemployment-study-2020-10), [Science News](https://www.sciencenews.org/article/asian-americans-science-data-invisible-demography-violence)

::: {.details summary="Abstract" group="faq"}
- The unemployment rate has sharply increased as a result of the lockdown associated with the spread of COVID-19. The negative effect of the lockdown is more conspicuous among the less-educated workers than the highly-educated workers. Because Asian Americans are more likely to have a bachelor or higher degree than any other racial group, they are expected to be relatively immune to the drop in employment unless the detrimental impact of the lockdown is severer for Asian Americans. Exploiting the panel aspect of the Current Population Survey – Merged Outgoing Rotation Group, we examine the changes in At-work status before and after the lockdown and between the lockdown and months of the reopening. The empirical results uncover that Asian Americans are more negatively affected by the lockdown than any other racial group, net of education, immigration status, and other covariates. Surprisingly, the negative impact of the lockdown is entirely concentrated on less-educated Asian Americans. Regardless of gender, less-educated Asian Americans are substantially more likely to lose employment than equally educated Whites and are not more likely to regain employment during the reopening months. Other less-educated racial minorities do not experience more reduction in At-work status than Whites, net of covariates. Highly-educated Asian Americans’ employment is equally affected by the lockdown with equally educated Whites.
:::

## 2020

### Has Generational Inequality Increased? Decomposition of the Between- and Within-Generational Inequality, 1999–2019
*Korean Journal of Sociology* 54(4): 161–205 (in Korean)  
Kim, ChangHwan and Andrew Taeho Kim  
김창환, 김태호. "세대 불평등은 증가하였는가? 세대 내, 세대 간 불평등 변화 요인 분석, 1999–2019."  
[Article](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002656961) · [Appendix](appendix/Kim_Kim2020_Appendix.pdf)

::: {.details summary="Abstract" group="faq"}
- 세대 불평등이 증가하였다는 기존 연구는 주로 가계동향조사를 이용하여 연령 효과를 측정하였다. 하지만 기존 방법은 교육, 가구 구성 등의 공변수를 통제하지 않아 생략변수편향으로부터 자유롭지 않다. 세대 간 불평등의 증감이 세대 분포의 변화 때문인지 세대 간 소득격차에 의한 것인지도 구분하지 않고 있다. 노동시장에서의 세대 불평등을 측정하기 위해서는 개인 노동시장 소득에 기반하여 세대 효과를 추정하여야 하지만 기존 연구는 대부분 가구소득에 기반하고 있다. 본 연구는 1999~2019년 가계동향조사를 개인단위 노동시장 소득 자료로 전환하여 소득 불평등에 영향을 끼치는 세대 간 소득 격차의 순효과를 분석한다. 분석 결과, 세대 간 불평등이 증가했다는 증거를 찾을 수 없었다. 핵심노동인구를 대상으로 개인 노동시장 소득 불평등을 세대 간, 세대 내 불평등으로 요소분해한 결과 세대 내 불평등은 줄었지만, 세대 간 불평등은 증가하지 않았다. 소득 불평등 변화를 연령과 교육 효과를 포함한 다변량 요인들의 구성효과와 순효과로 좀 더 세분하여 요소분해하였지만, 마찬가지로 연령 효과가 증가하였다는 증거를 찾을 수 없었다. 86세대의 경제지배권 강화가 소득 불평등 증가의 원인이라는 증거도 찾을 수 없었다. 86세대의 소득이 증가하였지만, 그 효과는 소득상층 노동시장이 아니라 소득하층 노동시장에서 지배적이었다. 2009년 이후 세대 불평등의 증가는 핵심노동인구 내부의 연령 간 소득 격차 증가 때문이 아니라 고령인구의 구성 효과, 그 중에서도 저학력 고령인구의 구성 효과 때문이다. 2009년 이후 증가한 세대 불평등은 고령인구의 증가로 인한 착시이지 핵심노동인구의 개인 노동시장 소득 불평등 증가 때문이 아니다. 이러한 결과는 세대론으로 전반적인 소득 불평등 변화를 설명하는 기획의 타당성을 의심하게 만든다.

- Prior studies on the generational inequality analyzed household income using the Household Income and Expenditure Survey (HIES) and argued that the between-generational earnings gap has increased. Generational inequality, however, should be measured based on the individual labor market earnings. The results of previous studies may suffer from the omitted variable bias as they failed to control for relevant covariates. Prior studies did not distinguish the net effect of generation on earnings from the effect associated with the change in age composition. In this study, we estimate individual labor market earnings using the 1999~2019 HIES and assess whether the net effect of generation has increased in accounting for earnings inequality. Our empirical results show that contrary to the popular perception and prior studies, between-generation inequality has not grown. The detailed decomposition results which control for education and other covariates indicate that the growth of between-generational inequality is fully attributable to the increase in the size of the older population. The net effect of generation did not change. No evidence supports that the dominance of the 86 Generation at the upper labor market causes the growth in earnings inequality either. The relative increase in earnings among the 86 Generation is evident only at the lower part of the earnings distribution. These results cast serious doubt on the validity of the claim that generation is a key structural dimension of earnings inequality in South Korea.
:::

## 2018

### Effects of Neighborhood Inequality on the Relative Distance between Objective Position and Subjective Identification
*International Journal of Japanese Sociology* 27(1): 85–106  
Kim, Andrew Taeho, Muncho Kim, and Seungho Ryu  
[Article](https://doi.org/10.1111/ijjs.12073)

## 2015

### Enhanced Complexity and Systems Theory: T. Parsons and N. Luhmann
*Korean Journal of Converging Humanities* 3(2): 77–90 (in Korean)  
Kim, Andrew Taeho  
김태호. "복잡성의 증대와 체계이론의 전환: 파슨스(T. Parsons)와 루만(N. Luhmann)의 비교를 중심으로."  
[Article](https://doi.org/10.14729/converging.k.2015.3.2.77)

### On Alienation in the Age of Uncertainty: Changes in Academic Sensibility
*Korean Journal of Converging Humanities* 3(1): 7–24 (in Korean)  
Kim, Andrew Taeho  
김태호. "불확실성 시대의 낯설어짐에 대해서: 학문적 감수성의 변화를 중심으로."  
[Article](https://doi.org/10.14729/converging.k.2015.3.1.7)

## 2014

### The Communication Adaptiveness and Power Dynamics of the State, the Market, and Civil Society in the Information Age: The Case of Korea
*Information, Communication & Society* 17(8): 956–973  
Kim, Jongkil, Jongtae Kim, and Andrew Taeho Kim  
[Article](https://doi.org/10.1080/1369118X.2013.869241)
